

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findresim.cmake")
# Global approach
set(resim_FOUND 1)
set(resim_VERSION "1.0.0")

find_package_handle_standard_args(resim REQUIRED_VARS
                                  resim_VERSION VERSION_VAR resim_VERSION)
mark_as_advanced(resim_FOUND resim_VERSION)


set(resim_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/resim/include")
set(resim_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/resim/include")
set(resim_INCLUDES "${CMAKE_CURRENT_LIST_DIR}/resim/include")
set(resim_RES_DIRS )
set(resim_DEFINITIONS )
set(resim_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(resim_COMPILE_DEFINITIONS )
set(resim_COMPILE_OPTIONS_LIST "" "")
set(resim_COMPILE_OPTIONS_C "")
set(resim_COMPILE_OPTIONS_CXX "")
set(resim_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(resim_LIBRARIES "") # Will be filled later
set(resim_LIBS "") # Same as resim_LIBRARIES
set(resim_SYSTEM_LIBS )
set(resim_FRAMEWORK_DIRS )
set(resim_FRAMEWORKS )
set(resim_FRAMEWORKS_FOUND "") # Will be filled later
set(resim_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(resim_FRAMEWORKS_FOUND "${resim_FRAMEWORKS}" "${resim_FRAMEWORK_DIRS}")

mark_as_advanced(resim_INCLUDE_DIRS
                 resim_INCLUDE_DIR
                 resim_INCLUDES
                 resim_DEFINITIONS
                 resim_LINKER_FLAGS_LIST
                 resim_COMPILE_DEFINITIONS
                 resim_COMPILE_OPTIONS_LIST
                 resim_LIBRARIES
                 resim_LIBS
                 resim_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to resim_LIBS and resim_LIBRARY_LIST
set(resim_LIBRARY_LIST resimcompressedtoudp resimcompression resimdecompression resimdecompressionpointcloud resimdetector resimdetectorcompression resiminterfaces resimpointcloud resimudptocompressed)
set(resim_LIB_DIRS "${CMAKE_CURRENT_LIST_DIR}/resim/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_resim_DEPENDENCIES "${resim_FRAMEWORKS_FOUND} ${resim_SYSTEM_LIBS} CapnProto::CapnProto")

conan_package_library_targets("${resim_LIBRARY_LIST}"  # libraries
                              "${resim_LIB_DIRS}"      # package_libdir
                              "${_resim_DEPENDENCIES}"  # deps
                              resim_LIBRARIES            # out_libraries
                              resim_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "resim")                                      # package_name

set(resim_LIBS ${resim_LIBRARIES})

foreach(_FRAMEWORK ${resim_FRAMEWORKS_FOUND})
    list(APPEND resim_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND resim_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${resim_SYSTEM_LIBS})
    list(APPEND resim_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND resim_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(resim_LIBRARIES_TARGETS "${resim_LIBRARIES_TARGETS};CapnProto::CapnProto")
set(resim_LIBRARIES "${resim_LIBRARIES};CapnProto::CapnProto")

set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/resim/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "${CMAKE_CURRENT_LIST_DIR}/resim/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET resim::resim)
        add_library(resim::resim INTERFACE IMPORTED)
        if(resim_INCLUDE_DIRS)
            set_target_properties(resim::resim PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${resim_INCLUDE_DIRS}")
        endif()
        set_property(TARGET resim::resim PROPERTY INTERFACE_LINK_LIBRARIES
                     "${resim_LIBRARIES_TARGETS};${resim_LINKER_FLAGS_LIST}")
        set_property(TARGET resim::resim PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${resim_COMPILE_DEFINITIONS})
        set_property(TARGET resim::resim PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${resim_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT CapnProto_FOUND)
            find_dependency(CapnProto REQUIRED)
        else()
            message(STATUS "Dependency CapnProto already found")
        endif()

    endif()
endif()

foreach(_BUILD_MODULE_PATH ${resim_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
