// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: detector.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 9001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "roic705.capnp.h"
#include "semver.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(eb63060ed954eeab);

}  // namespace schemas
}  // namespace capnp

namespace ReSim {
namespace Schemas {

struct Detector {
  Detector() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(eb63060ed954eeab, 0, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Detector::Reader {
public:
  typedef Detector Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSemVer() const;
  inline  ::ReSim::Schemas::SemVer::Reader getSemVer() const;

  inline bool hasFrames() const;
  inline  ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>::Reader getFrames() const;

  inline bool hasDetectorConfig() const;
  inline  ::ReSim::Schemas::Roic705::Config::Reader getDetectorConfig() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Detector::Builder {
public:
  typedef Detector Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSemVer();
  inline  ::ReSim::Schemas::SemVer::Builder getSemVer();
  inline void setSemVer( ::ReSim::Schemas::SemVer::Reader value);
  inline  ::ReSim::Schemas::SemVer::Builder initSemVer();
  inline void adoptSemVer(::capnp::Orphan< ::ReSim::Schemas::SemVer>&& value);
  inline ::capnp::Orphan< ::ReSim::Schemas::SemVer> disownSemVer();

  inline bool hasFrames();
  inline  ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>::Builder getFrames();
  inline void setFrames( ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>::Builder initFrames(unsigned int size);
  inline void adoptFrames(::capnp::Orphan< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>> disownFrames();

  inline bool hasDetectorConfig();
  inline  ::ReSim::Schemas::Roic705::Config::Builder getDetectorConfig();
  inline void setDetectorConfig( ::ReSim::Schemas::Roic705::Config::Reader value);
  inline  ::ReSim::Schemas::Roic705::Config::Builder initDetectorConfig();
  inline void adoptDetectorConfig(::capnp::Orphan< ::ReSim::Schemas::Roic705::Config>&& value);
  inline ::capnp::Orphan< ::ReSim::Schemas::Roic705::Config> disownDetectorConfig();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Detector::Pipeline {
public:
  typedef Detector Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::ReSim::Schemas::SemVer::Pipeline getSemVer();
  inline  ::ReSim::Schemas::Roic705::Config::Pipeline getDetectorConfig();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool Detector::Reader::hasSemVer() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Detector::Builder::hasSemVer() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::ReSim::Schemas::SemVer::Reader Detector::Reader::getSemVer() const {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::SemVer>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS),
        ::capnp::schemas::bp_eb63060ed954eeab + 46);
}
inline  ::ReSim::Schemas::SemVer::Builder Detector::Builder::getSemVer() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::SemVer>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS),
        ::capnp::schemas::bp_eb63060ed954eeab + 46);
}
#if !CAPNP_LITE
inline  ::ReSim::Schemas::SemVer::Pipeline Detector::Pipeline::getSemVer() {
  return  ::ReSim::Schemas::SemVer::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void Detector::Builder::setSemVer( ::ReSim::Schemas::SemVer::Reader value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::SemVer>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::ReSim::Schemas::SemVer::Builder Detector::Builder::initSemVer() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::SemVer>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Detector::Builder::adoptSemVer(
    ::capnp::Orphan< ::ReSim::Schemas::SemVer>&& value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::SemVer>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ReSim::Schemas::SemVer> Detector::Builder::disownSemVer() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::SemVer>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Detector::Reader::hasFrames() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Detector::Builder::hasFrames() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>::Reader Detector::Reader::getFrames() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>::Builder Detector::Builder::getFrames() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Detector::Builder::setFrames( ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>::Builder Detector::Builder::initFrames(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void Detector::Builder::adoptFrames(
    ::capnp::Orphan< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>> Detector::Builder::disownFrames() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::ReSim::Schemas::Roic705::RoicFrame< ::ReSim::Schemas::Roic705::SiteFrame>,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool Detector::Reader::hasDetectorConfig() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool Detector::Builder::hasDetectorConfig() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::ReSim::Schemas::Roic705::Config::Reader Detector::Reader::getDetectorConfig() const {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::Config>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::ReSim::Schemas::Roic705::Config::Builder Detector::Builder::getDetectorConfig() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::Config>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::ReSim::Schemas::Roic705::Config::Pipeline Detector::Pipeline::getDetectorConfig() {
  return  ::ReSim::Schemas::Roic705::Config::Pipeline(_typeless.getPointerField(2));
}
#endif  // !CAPNP_LITE
inline void Detector::Builder::setDetectorConfig( ::ReSim::Schemas::Roic705::Config::Reader value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::Config>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::ReSim::Schemas::Roic705::Config::Builder Detector::Builder::initDetectorConfig() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::Config>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void Detector::Builder::adoptDetectorConfig(
    ::capnp::Orphan< ::ReSim::Schemas::Roic705::Config>&& value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::Config>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ReSim::Schemas::Roic705::Config> Detector::Builder::disownDetectorConfig() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::Config>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

}  // namespace
}  // namespace

CAPNP_END_HEADER

