// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: roic705.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 9001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "tdc_metadata.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(f2bd724f331e47f0);
CAPNP_DECLARE_SCHEMA(8751bd58731a6bdf);
CAPNP_DECLARE_SCHEMA(9141bea0d22491a8);
CAPNP_DECLARE_SCHEMA(cc94918dbac4f6c2);
CAPNP_DECLARE_SCHEMA(dbcbf41cf5fac052);
CAPNP_DECLARE_SCHEMA(d5eeb6e9b0d566a9);
CAPNP_DECLARE_SCHEMA(f13a27fa919cccec);
CAPNP_DECLARE_SCHEMA(cf1a543f951e4ce6);
CAPNP_DECLARE_SCHEMA(84fd28c606eedbc5);
CAPNP_DECLARE_SCHEMA(a5106fbc015dc0c5);
CAPNP_DECLARE_SCHEMA(dbc842058baf827d);

}  // namespace schemas
}  // namespace capnp

namespace ReSim {
namespace Schemas {

struct Roic705 {
  Roic705() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  static constexpr  ::uint8_t NUM_SITES = 2u;
  struct SiteConfig;
  struct Config;
  struct SiteFrame;
  template <typename RoicData = ::capnp::AnyPointer>
  struct RoicFrame;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f2bd724f331e47f0, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Roic705::SiteConfig {
  SiteConfig() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  static constexpr  ::uint8_t NUM_THRESHOLDS_OFFSETS = 23u;
  static constexpr  ::uint8_t SITE_A = 0u;
  static constexpr  ::uint8_t SITE_B = 1u;
  struct ComparatorConfig;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9141bea0d22491a8, 1, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Roic705::SiteConfig::ComparatorConfig {
  ComparatorConfig() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f13a27fa919cccec, 1, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Roic705::Config {
  Config() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(cf1a543f951e4ce6, 2, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Roic705::SiteFrame {
  SiteFrame() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  static constexpr  ::uint8_t NUM_TDCS_PER_ROIC_FRAME = 252u;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(84fd28c606eedbc5, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

template <typename RoicData>
struct Roic705::RoicFrame {
  RoicFrame() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(dbc842058baf827d, 0, 3)
    #if !CAPNP_LITE
    static const ::capnp::_::RawBrandedSchema::Scope brandScopes[];
    static const ::capnp::_::RawBrandedSchema::Binding brandBindings[];
    static const ::capnp::_::RawBrandedSchema specificBrand;
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return ::capnp::_::ChooseBrand<_capnpPrivate, RoicData>::brand(); }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Roic705::Reader {
public:
  typedef Roic705 Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Roic705::Builder {
public:
  typedef Roic705 Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Roic705::Pipeline {
public:
  typedef Roic705 Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Roic705::SiteConfig::Reader {
public:
  typedef SiteConfig Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline typename ComparatorConfig::Reader getComparatorConfig() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Roic705::SiteConfig::Builder {
public:
  typedef SiteConfig Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline typename ComparatorConfig::Builder getComparatorConfig();
  inline typename ComparatorConfig::Builder initComparatorConfig();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Roic705::SiteConfig::Pipeline {
public:
  typedef SiteConfig Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline typename ComparatorConfig::Pipeline getComparatorConfig();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Roic705::SiteConfig::ComparatorConfig::Reader {
public:
  typedef ComparatorConfig Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasThresholds() const;
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader getThresholds() const;

  inline bool hasOffsets() const;
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader getOffsets() const;

  inline  ::uint16_t getCoarseMult() const;

  inline  ::uint16_t getFineMult() const;

  inline bool hasNumBaseline() const;
  inline  ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>::Reader getNumBaseline() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Roic705::SiteConfig::ComparatorConfig::Builder {
public:
  typedef ComparatorConfig Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasThresholds();
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder getThresholds();
  inline void setThresholds( ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setThresholds(::kj::ArrayPtr<const  ::uint16_t> value);
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder initThresholds(unsigned int size);
  inline void adoptThresholds(::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>> disownThresholds();

  inline bool hasOffsets();
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder getOffsets();
  inline void setOffsets( ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setOffsets(::kj::ArrayPtr<const  ::uint16_t> value);
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder initOffsets(unsigned int size);
  inline void adoptOffsets(::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>> disownOffsets();

  inline  ::uint16_t getCoarseMult();
  inline void setCoarseMult( ::uint16_t value);

  inline  ::uint16_t getFineMult();
  inline void setFineMult( ::uint16_t value);

  inline bool hasNumBaseline();
  inline  ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>::Builder getNumBaseline();
  inline void setNumBaseline( ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setNumBaseline(::kj::ArrayPtr<const  ::uint8_t> value);
  inline  ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>::Builder initNumBaseline(unsigned int size);
  inline void adoptNumBaseline(::capnp::Orphan< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>> disownNumBaseline();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Roic705::SiteConfig::ComparatorConfig::Pipeline {
public:
  typedef ComparatorConfig Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Roic705::Config::Reader {
public:
  typedef Config Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSiteA() const;
  inline  ::ReSim::Schemas::Roic705::SiteConfig::Reader getSiteA() const;

  inline bool hasSiteB() const;
  inline  ::ReSim::Schemas::Roic705::SiteConfig::Reader getSiteB() const;

  inline  ::uint32_t getDetectorSN() const;

  inline  ::uint16_t getPna() const;

  inline  ::uint32_t getPrf() const;

  inline  ::uint8_t getConfigId() const;

  inline  ::uint8_t getVersion() const;

  inline  ::uint8_t getSubVersion() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Roic705::Config::Builder {
public:
  typedef Config Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSiteA();
  inline  ::ReSim::Schemas::Roic705::SiteConfig::Builder getSiteA();
  inline void setSiteA( ::ReSim::Schemas::Roic705::SiteConfig::Reader value);
  inline  ::ReSim::Schemas::Roic705::SiteConfig::Builder initSiteA();
  inline void adoptSiteA(::capnp::Orphan< ::ReSim::Schemas::Roic705::SiteConfig>&& value);
  inline ::capnp::Orphan< ::ReSim::Schemas::Roic705::SiteConfig> disownSiteA();

  inline bool hasSiteB();
  inline  ::ReSim::Schemas::Roic705::SiteConfig::Builder getSiteB();
  inline void setSiteB( ::ReSim::Schemas::Roic705::SiteConfig::Reader value);
  inline  ::ReSim::Schemas::Roic705::SiteConfig::Builder initSiteB();
  inline void adoptSiteB(::capnp::Orphan< ::ReSim::Schemas::Roic705::SiteConfig>&& value);
  inline ::capnp::Orphan< ::ReSim::Schemas::Roic705::SiteConfig> disownSiteB();

  inline  ::uint32_t getDetectorSN();
  inline void setDetectorSN( ::uint32_t value);

  inline  ::uint16_t getPna();
  inline void setPna( ::uint16_t value);

  inline  ::uint32_t getPrf();
  inline void setPrf( ::uint32_t value);

  inline  ::uint8_t getConfigId();
  inline void setConfigId( ::uint8_t value);

  inline  ::uint8_t getVersion();
  inline void setVersion( ::uint8_t value);

  inline  ::uint8_t getSubVersion();
  inline void setSubVersion( ::uint8_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Roic705::Config::Pipeline {
public:
  typedef Config Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::ReSim::Schemas::Roic705::SiteConfig::Pipeline getSiteA();
  inline  ::ReSim::Schemas::Roic705::SiteConfig::Pipeline getSiteB();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Roic705::SiteFrame::Reader {
public:
  typedef SiteFrame Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasTdcs() const;
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader getTdcs() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Roic705::SiteFrame::Builder {
public:
  typedef SiteFrame Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasTdcs();
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder getTdcs();
  inline void setTdcs( ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setTdcs(::kj::ArrayPtr<const  ::uint16_t> value);
  inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder initTdcs(unsigned int size);
  inline void adoptTdcs(::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>> disownTdcs();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Roic705::SiteFrame::Pipeline {
public:
  typedef SiteFrame Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

template <typename RoicData>
class Roic705::RoicFrame<RoicData>::Reader {
public:
  typedef RoicFrame Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  template <typename RoicData2 = ::capnp::AnyPointer>
  typename RoicFrame<RoicData2>::Reader asGeneric() {
    return typename RoicFrame<RoicData2>::Reader(_reader);
  }

  inline bool hasMetadata() const;
  inline  ::ReSim::Schemas::TdcMetadata::Reader getMetadata() const;

  inline bool hasSiteA() const;
  inline  ::capnp::ReaderFor<RoicData> getSiteA() const;

  inline bool hasSiteB() const;
  inline  ::capnp::ReaderFor<RoicData> getSiteB() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

template <typename RoicData>
class Roic705::RoicFrame<RoicData>::Builder {
public:
  typedef RoicFrame Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  template <typename RoicData2 = ::capnp::AnyPointer>
  typename RoicFrame<RoicData2>::Builder asGeneric() {
    return typename RoicFrame<RoicData2>::Builder(_builder);
  }

  inline bool hasMetadata();
  inline  ::ReSim::Schemas::TdcMetadata::Builder getMetadata();
  inline void setMetadata( ::ReSim::Schemas::TdcMetadata::Reader value);
  inline  ::ReSim::Schemas::TdcMetadata::Builder initMetadata();
  inline void adoptMetadata(::capnp::Orphan< ::ReSim::Schemas::TdcMetadata>&& value);
  inline ::capnp::Orphan< ::ReSim::Schemas::TdcMetadata> disownMetadata();

  inline bool hasSiteA();
  inline  ::capnp::BuilderFor<RoicData> getSiteA();
  inline void setSiteA( ::capnp::ReaderFor<RoicData> value);
  inline  ::capnp::BuilderFor<RoicData> initSiteA();
  inline  ::capnp::BuilderFor<RoicData> initSiteA(unsigned int size);
  inline void adoptSiteA(::capnp::Orphan<RoicData>&& value);
  inline ::capnp::Orphan<RoicData> disownSiteA();

  inline bool hasSiteB();
  inline  ::capnp::BuilderFor<RoicData> getSiteB();
  inline void setSiteB( ::capnp::ReaderFor<RoicData> value);
  inline  ::capnp::BuilderFor<RoicData> initSiteB();
  inline  ::capnp::BuilderFor<RoicData> initSiteB(unsigned int size);
  inline void adoptSiteB(::capnp::Orphan<RoicData>&& value);
  inline ::capnp::Orphan<RoicData> disownSiteB();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
template <typename RoicData>
class Roic705::RoicFrame<RoicData>::Pipeline {
public:
  typedef RoicFrame Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::ReSim::Schemas::TdcMetadata::Pipeline getMetadata();
  inline  ::capnp::PipelineFor<RoicData> getSiteA();
  inline  ::capnp::PipelineFor<RoicData> getSiteB();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline typename Roic705::SiteConfig::ComparatorConfig::Reader Roic705::SiteConfig::Reader::getComparatorConfig() const {
  return typename Roic705::SiteConfig::ComparatorConfig::Reader(_reader);
}
inline typename Roic705::SiteConfig::ComparatorConfig::Builder Roic705::SiteConfig::Builder::getComparatorConfig() {
  return typename Roic705::SiteConfig::ComparatorConfig::Builder(_builder);
}
#if !CAPNP_LITE
inline typename Roic705::SiteConfig::ComparatorConfig::Pipeline Roic705::SiteConfig::Pipeline::getComparatorConfig() {
  return typename Roic705::SiteConfig::ComparatorConfig::Pipeline(_typeless.noop());
}
#endif  // !CAPNP_LITE
inline typename Roic705::SiteConfig::ComparatorConfig::Builder Roic705::SiteConfig::Builder::initComparatorConfig() {
  _builder.setDataField< ::uint16_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint16_t>(::capnp::bounded<1>() * ::capnp::ELEMENTS, 0);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<2>() * ::capnp::POINTERS).clear();
  return typename Roic705::SiteConfig::ComparatorConfig::Builder(_builder);
}
inline bool Roic705::SiteConfig::ComparatorConfig::Reader::hasThresholds() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Roic705::SiteConfig::ComparatorConfig::Builder::hasThresholds() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader Roic705::SiteConfig::ComparatorConfig::Reader::getThresholds() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder Roic705::SiteConfig::ComparatorConfig::Builder::getThresholds() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::setThresholds( ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::setThresholds(::kj::ArrayPtr<const  ::uint16_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder Roic705::SiteConfig::ComparatorConfig::Builder::initThresholds(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::adoptThresholds(
    ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>> Roic705::SiteConfig::ComparatorConfig::Builder::disownThresholds() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Roic705::SiteConfig::ComparatorConfig::Reader::hasOffsets() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Roic705::SiteConfig::ComparatorConfig::Builder::hasOffsets() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader Roic705::SiteConfig::ComparatorConfig::Reader::getOffsets() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder Roic705::SiteConfig::ComparatorConfig::Builder::getOffsets() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::setOffsets( ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::setOffsets(::kj::ArrayPtr<const  ::uint16_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder Roic705::SiteConfig::ComparatorConfig::Builder::initOffsets(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::adoptOffsets(
    ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>> Roic705::SiteConfig::ComparatorConfig::Builder::disownOffsets() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline  ::uint16_t Roic705::SiteConfig::ComparatorConfig::Reader::getCoarseMult() const {
  return _reader.getDataField< ::uint16_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint16_t Roic705::SiteConfig::ComparatorConfig::Builder::getCoarseMult() {
  return _builder.getDataField< ::uint16_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::setCoarseMult( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint16_t Roic705::SiteConfig::ComparatorConfig::Reader::getFineMult() const {
  return _reader.getDataField< ::uint16_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint16_t Roic705::SiteConfig::ComparatorConfig::Builder::getFineMult() {
  return _builder.getDataField< ::uint16_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::setFineMult( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool Roic705::SiteConfig::ComparatorConfig::Reader::hasNumBaseline() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool Roic705::SiteConfig::ComparatorConfig::Builder::hasNumBaseline() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>::Reader Roic705::SiteConfig::ComparatorConfig::Reader::getNumBaseline() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS),
        ::capnp::schemas::bp_f13a27fa919cccec + 111);
}
inline  ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>::Builder Roic705::SiteConfig::ComparatorConfig::Builder::getNumBaseline() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS),
        ::capnp::schemas::bp_f13a27fa919cccec + 111);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::setNumBaseline( ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::setNumBaseline(::kj::ArrayPtr<const  ::uint8_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>::Builder Roic705::SiteConfig::ComparatorConfig::Builder::initNumBaseline(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void Roic705::SiteConfig::ComparatorConfig::Builder::adoptNumBaseline(
    ::capnp::Orphan< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>> Roic705::SiteConfig::ComparatorConfig::Builder::disownNumBaseline() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint8_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool Roic705::Config::Reader::hasSiteA() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Roic705::Config::Builder::hasSiteA() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::ReSim::Schemas::Roic705::SiteConfig::Reader Roic705::Config::Reader::getSiteA() const {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::ReSim::Schemas::Roic705::SiteConfig::Builder Roic705::Config::Builder::getSiteA() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::ReSim::Schemas::Roic705::SiteConfig::Pipeline Roic705::Config::Pipeline::getSiteA() {
  return  ::ReSim::Schemas::Roic705::SiteConfig::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void Roic705::Config::Builder::setSiteA( ::ReSim::Schemas::Roic705::SiteConfig::Reader value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::ReSim::Schemas::Roic705::SiteConfig::Builder Roic705::Config::Builder::initSiteA() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Roic705::Config::Builder::adoptSiteA(
    ::capnp::Orphan< ::ReSim::Schemas::Roic705::SiteConfig>&& value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ReSim::Schemas::Roic705::SiteConfig> Roic705::Config::Builder::disownSiteA() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Roic705::Config::Reader::hasSiteB() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Roic705::Config::Builder::hasSiteB() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::ReSim::Schemas::Roic705::SiteConfig::Reader Roic705::Config::Reader::getSiteB() const {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::ReSim::Schemas::Roic705::SiteConfig::Builder Roic705::Config::Builder::getSiteB() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::ReSim::Schemas::Roic705::SiteConfig::Pipeline Roic705::Config::Pipeline::getSiteB() {
  return  ::ReSim::Schemas::Roic705::SiteConfig::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void Roic705::Config::Builder::setSiteB( ::ReSim::Schemas::Roic705::SiteConfig::Reader value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::ReSim::Schemas::Roic705::SiteConfig::Builder Roic705::Config::Builder::initSiteB() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Roic705::Config::Builder::adoptSiteB(
    ::capnp::Orphan< ::ReSim::Schemas::Roic705::SiteConfig>&& value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ReSim::Schemas::Roic705::SiteConfig> Roic705::Config::Builder::disownSiteB() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::Roic705::SiteConfig>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline  ::uint32_t Roic705::Config::Reader::getDetectorSN() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Roic705::Config::Builder::getDetectorSN() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Roic705::Config::Builder::setDetectorSN( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint16_t Roic705::Config::Reader::getPna() const {
  return _reader.getDataField< ::uint16_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint16_t Roic705::Config::Builder::getPna() {
  return _builder.getDataField< ::uint16_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Roic705::Config::Builder::setPna( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t Roic705::Config::Reader::getPrf() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Roic705::Config::Builder::getPrf() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Roic705::Config::Builder::setPrf( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::uint8_t Roic705::Config::Reader::getConfigId() const {
  return _reader.getDataField< ::uint8_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, 1u);
}

inline  ::uint8_t Roic705::Config::Builder::getConfigId() {
  return _builder.getDataField< ::uint8_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, 1u);
}
inline void Roic705::Config::Builder::setConfigId( ::uint8_t value) {
  _builder.setDataField< ::uint8_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, value, 1u);
}

inline  ::uint8_t Roic705::Config::Reader::getVersion() const {
  return _reader.getDataField< ::uint8_t>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS);
}

inline  ::uint8_t Roic705::Config::Builder::getVersion() {
  return _builder.getDataField< ::uint8_t>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS);
}
inline void Roic705::Config::Builder::setVersion( ::uint8_t value) {
  _builder.setDataField< ::uint8_t>(
      ::capnp::bounded<7>() * ::capnp::ELEMENTS, value);
}

inline  ::uint8_t Roic705::Config::Reader::getSubVersion() const {
  return _reader.getDataField< ::uint8_t>(
      ::capnp::bounded<12>() * ::capnp::ELEMENTS);
}

inline  ::uint8_t Roic705::Config::Builder::getSubVersion() {
  return _builder.getDataField< ::uint8_t>(
      ::capnp::bounded<12>() * ::capnp::ELEMENTS);
}
inline void Roic705::Config::Builder::setSubVersion( ::uint8_t value) {
  _builder.setDataField< ::uint8_t>(
      ::capnp::bounded<12>() * ::capnp::ELEMENTS, value);
}

inline bool Roic705::SiteFrame::Reader::hasTdcs() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Roic705::SiteFrame::Builder::hasTdcs() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader Roic705::SiteFrame::Reader::getTdcs() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder Roic705::SiteFrame::Builder::getTdcs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Roic705::SiteFrame::Builder::setTdcs( ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline void Roic705::SiteFrame::Builder::setTdcs(::kj::ArrayPtr<const  ::uint16_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>::Builder Roic705::SiteFrame::Builder::initTdcs(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Roic705::SiteFrame::Builder::adoptTdcs(
    ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>> Roic705::SiteFrame::Builder::disownTdcs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint16_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

template <typename RoicData>
inline bool Roic705::RoicFrame<RoicData>::Reader::hasMetadata() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
template <typename RoicData>
inline bool Roic705::RoicFrame<RoicData>::Builder::hasMetadata() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
template <typename RoicData>
inline  ::ReSim::Schemas::TdcMetadata::Reader Roic705::RoicFrame<RoicData>::Reader::getMetadata() const {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::TdcMetadata>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
template <typename RoicData>
inline  ::ReSim::Schemas::TdcMetadata::Builder Roic705::RoicFrame<RoicData>::Builder::getMetadata() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::TdcMetadata>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
template <typename RoicData>
inline  ::ReSim::Schemas::TdcMetadata::Pipeline Roic705::RoicFrame<RoicData>::Pipeline::getMetadata() {
  return  ::ReSim::Schemas::TdcMetadata::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
template <typename RoicData>
inline void Roic705::RoicFrame<RoicData>::Builder::setMetadata( ::ReSim::Schemas::TdcMetadata::Reader value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::TdcMetadata>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
template <typename RoicData>
inline  ::ReSim::Schemas::TdcMetadata::Builder Roic705::RoicFrame<RoicData>::Builder::initMetadata() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::TdcMetadata>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
template <typename RoicData>
inline void Roic705::RoicFrame<RoicData>::Builder::adoptMetadata(
    ::capnp::Orphan< ::ReSim::Schemas::TdcMetadata>&& value) {
  ::capnp::_::PointerHelpers< ::ReSim::Schemas::TdcMetadata>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
template <typename RoicData>
inline ::capnp::Orphan< ::ReSim::Schemas::TdcMetadata> Roic705::RoicFrame<RoicData>::Builder::disownMetadata() {
  return ::capnp::_::PointerHelpers< ::ReSim::Schemas::TdcMetadata>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

template <typename RoicData>
inline bool Roic705::RoicFrame<RoicData>::Reader::hasSiteA() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
template <typename RoicData>
inline bool Roic705::RoicFrame<RoicData>::Builder::hasSiteA() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
template <typename RoicData>
inline  ::capnp::ReaderFor<RoicData> Roic705::RoicFrame<RoicData>::Reader::getSiteA() const {
  return ::capnp::_::PointerHelpers<RoicData>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
template <typename RoicData>
inline  ::capnp::BuilderFor<RoicData> Roic705::RoicFrame<RoicData>::Builder::getSiteA() {
  return ::capnp::_::PointerHelpers<RoicData>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
template <typename RoicData>
inline  ::capnp::PipelineFor<RoicData> Roic705::RoicFrame<RoicData>::Pipeline::getSiteA() {
  return  ::capnp::PipelineFor<RoicData>(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
template <typename RoicData>
inline void Roic705::RoicFrame<RoicData>::Builder::setSiteA( ::capnp::ReaderFor<RoicData> value) {
  ::capnp::_::PointerHelpers<RoicData>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
template <typename RoicData>
inline  ::capnp::BuilderFor<RoicData> Roic705::RoicFrame<RoicData>::Builder::initSiteA() {
  return ::capnp::_::PointerHelpers<RoicData>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
template <typename RoicData>
inline  ::capnp::BuilderFor<RoicData> Roic705::RoicFrame<RoicData>::Builder::initSiteA(unsigned int size) {
  return ::capnp::_::PointerHelpers<RoicData>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
template <typename RoicData>
inline void Roic705::RoicFrame<RoicData>::Builder::adoptSiteA(
    ::capnp::Orphan<RoicData>&& value) {
  ::capnp::_::PointerHelpers<RoicData>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
template <typename RoicData>
inline ::capnp::Orphan<RoicData> Roic705::RoicFrame<RoicData>::Builder::disownSiteA() {
  return ::capnp::_::PointerHelpers<RoicData>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

template <typename RoicData>
inline bool Roic705::RoicFrame<RoicData>::Reader::hasSiteB() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
template <typename RoicData>
inline bool Roic705::RoicFrame<RoicData>::Builder::hasSiteB() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
template <typename RoicData>
inline  ::capnp::ReaderFor<RoicData> Roic705::RoicFrame<RoicData>::Reader::getSiteB() const {
  return ::capnp::_::PointerHelpers<RoicData>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
template <typename RoicData>
inline  ::capnp::BuilderFor<RoicData> Roic705::RoicFrame<RoicData>::Builder::getSiteB() {
  return ::capnp::_::PointerHelpers<RoicData>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
template <typename RoicData>
inline  ::capnp::PipelineFor<RoicData> Roic705::RoicFrame<RoicData>::Pipeline::getSiteB() {
  return  ::capnp::PipelineFor<RoicData>(_typeless.getPointerField(2));
}
#endif  // !CAPNP_LITE
template <typename RoicData>
inline void Roic705::RoicFrame<RoicData>::Builder::setSiteB( ::capnp::ReaderFor<RoicData> value) {
  ::capnp::_::PointerHelpers<RoicData>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
template <typename RoicData>
inline  ::capnp::BuilderFor<RoicData> Roic705::RoicFrame<RoicData>::Builder::initSiteB() {
  return ::capnp::_::PointerHelpers<RoicData>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
template <typename RoicData>
inline  ::capnp::BuilderFor<RoicData> Roic705::RoicFrame<RoicData>::Builder::initSiteB(unsigned int size) {
  return ::capnp::_::PointerHelpers<RoicData>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
template <typename RoicData>
inline void Roic705::RoicFrame<RoicData>::Builder::adoptSiteB(
    ::capnp::Orphan<RoicData>&& value) {
  ::capnp::_::PointerHelpers<RoicData>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
template <typename RoicData>
inline ::capnp::Orphan<RoicData> Roic705::RoicFrame<RoicData>::Builder::disownSiteB() {
  return ::capnp::_::PointerHelpers<RoicData>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

// Roic705::RoicFrame<RoicData>
template <typename RoicData>
constexpr uint16_t Roic705::RoicFrame<RoicData>::_capnpPrivate::dataWordSize;
template <typename RoicData>
constexpr uint16_t Roic705::RoicFrame<RoicData>::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
template <typename RoicData>
constexpr ::capnp::Kind Roic705::RoicFrame<RoicData>::_capnpPrivate::kind;
template <typename RoicData>
constexpr ::capnp::_::RawSchema const* Roic705::RoicFrame<RoicData>::_capnpPrivate::schema;
template <typename RoicData>
const ::capnp::_::RawBrandedSchema::Scope Roic705::RoicFrame<RoicData>::_capnpPrivate::brandScopes[] = {
  { 0xdbc842058baf827d, brandBindings + 0, 1, false},
};
template <typename RoicData>
const ::capnp::_::RawBrandedSchema::Binding Roic705::RoicFrame<RoicData>::_capnpPrivate::brandBindings[] = {
  ::capnp::_::brandBindingFor<RoicData>(),
};
template <typename RoicData>
const ::capnp::_::RawBrandedSchema Roic705::RoicFrame<RoicData>::_capnpPrivate::specificBrand = {
  &::capnp::schemas::s_dbc842058baf827d, brandScopes, nullptr,
  1, 0, nullptr
};
#endif  // !CAPNP_LITE

}  // namespace
}  // namespace

CAPNP_END_HEADER

