recorder:
  ros__parameters:
    use_sim_time: false
    record:
      all: true
      is_discovery_disabled: false
      topic_polling_interval:
        sec: 0
        nsec: 10000000
      include_hidden_topics: true
      ignore_leaf_topics: false
      start_paused: false

    storage:
      uri: "/path/to/destination/folder"
      storage_id: "sqlite3"
      max_cache_size: 20000000